class CreateShopTrades < ActiveRecord::Migration
	def change
    create_table :shop_trades do |t|
    		t.integer  "user_id"
		    t.integer  "contact_id"
		    t.string   "status"
		    t.text     "comment"
		    t.decimal  "price", precision: 10, scale: 0
		    t.boolean  "active", default: true
		    t.datetime "destroyed_at"
		    t.datetime "created_at"
		    t.datetime "updated_at"
		    t.integer  "item_id"
		    t.string   "identifier"
		    t.integer  "percent"
		    t.string   "payment_service"
		    t.string   "payment_identifier"
		    t.string   "delivery_service"
		    t.string   "delivery_identifier"
		    t.text     "remark"
		    t.integer  "lock_version", default: 0
		    t.integer  "link_id"
		    t.string   "delivery_time"
		    t.string   "invoice_type"
		    t.string   "invoice_title"
		    t.string   "invoice_content"
		    t.integer  "click_id"
		    t.integer  "invoice_contact_id"
		    t.boolean  "receipted",                                                  :default => false, :null => false
		    t.datetime "receipted_at"
		    t.string   "delivery_phone"
		    t.integer  "editor_id"
		    t.integer  "audit_editor_id"
		    t.datetime "audit_at"
		    t.integer  "ship_editor_id"
		    t.datetime "ship_at"
		    t.integer  "freeze_editor_id"
		    t.datetime "freeze_at"
		    t.integer  "receipt_editor_id"
		    t.integer  "prepare_editor_id"
		    t.datetime "prepare_at"
		    t.integer  "original_id"
		    t.string   "invoice_delivery_service"
		    t.string   "invoice_delivery_identifier"
		    t.text     "invoice_remark"
		    t.datetime "delivery_received_at"
		    t.string   "checkout_token"
		    t.string   "checkout_comment"
		    t.string   "checkout_name"
		    t.integer  "delivery_receipted_amount"
		    t.datetime "delivery_receipted_at"
		    t.datetime "delivery_remitted_at"
		    t.integer  "delivery_settled_amount"
		    t.datetime "delivery_settled_at"
		    t.datetime "delivery_reconciled_at"
		    t.string   "client"
		    t.integer  "payment_price"
		    t.integer  "shop_id"
		    t.string   "shop_identifier"
		    t.text     "payment_return"
		    t.integer  "latest_link_id"
		    t.integer  "latest_click_id"
		    t.integer  "out_editor_id"
		    t.datetime "out_at"
			t.timestamps null: false
	    end
	end
end
