development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: weimall_dev
  pool: 5
  username: root
  password: 123456
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: weimall
  pool: 5
  username: root
  password: 123456
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: weimall
  pool: 5
  username: root
  password: 123456
